### PR TITLE
Refactor code (thanks to sourcery-ai)

### PR DESCRIPTION
**Pull request by kokonut27**
* Updated README to correct Repo name
* Updated README to better syntax-ed and easily readable

### CODE REVIEW

**Comment by TheSecondComing123** [comment]
@kokonut27 I approve all except for the sourcey-ai refactor.

**Comment by kokonut27** [comment]
Okay, let me undo it real quick :)

**Comment by kokonut27** [comment]
Also, @TheSecondComing123, is it supposed to be only accessible through forking or cloning the Repo, and then changing the code at `if __name__ == "__main__": ...`?

**Comment by TheSecondComing123** [comment]
@kokonut27  It's not supposed to be accessible. It's just that without it, I can't run python in pycharm.

**Comment by kokonut27** [comment]
Oh, okay. Thanks for the reply!

**Pull request merged**
